### ISSUE TITLE
Failing tests with master and 2.7.0

### ISSUE THREAD

**Issue by strzibny** [petergoldstein/dalli#439]
Hi, I am getting some errors/failures with master (and 2.7.0 as well):

```
$ testrb -Ilib test/test_*.rb
Testing with Rails 4.0.0
Using standard socket IO (ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux])
test/test_active_support.rb: cannot load such file -- connection_pool
Run options: -Ilib

# Running tests:

[ 6/96] Dalli::Cas::Client::using a live server#test_0005_handles CAS round-trip operationsFound memcached 1.4.15 in PATH
[ 8/96] Dalli::Cas::Client::using a live server#test_0002_supports multi-get with CAS = 0.02 s                
  1) Error:
Dalli::Cas::Client::using a live server#test_0002_supports multi-get with CAS:
NoMethodError: undefined method `second' for ["foo", 432345564227567616]:Array
    /home/strzibny/projects/dalli/test/test_cas_client.rb:44:in `block (5 levels) in <top (required)>'
    /home/strzibny/projects/dalli/test/test_cas_client.rb:43:in `each_pair'
    /home/strzibny/projects/dalli/test/test_cas_client.rb:43:in `block (4 levels) in <top (required)>'
    /home/strzibny/projects/dalli/test/memcached_mock.rb:76:in `memcached_cas'
    /home/strzibny/projects/dalli/test/test_cas_client.rb:32:in `block (3 levels) in <top (required)>'

[84/96] Sasl::a server requiring authentication#test_0001_fail SASL authentication with wrong optionsThis server is not built with SASL support.
 = 0.12 s
  2) Failure:
Sasl::a server requiring authentication#test_0001_fail SASL authentication with wrong options [/home/strzibny/projects/dalli/test/test_sasl.rb:45]:
[Dalli::DalliError] exception expected, not
Class: <Dalli::RingError>
Message: <"No server available">
---Backtrace---
/home/strzibny/projects/dalli/lib/dalli/ring.rb:45:in `server_for_key'
/home/strzibny/projects/dalli/lib/dalli/client.rb:328:in `perform'
/home/strzibny/projects/dalli/lib/dalli/client.rb:103:in `set'
/home/strzibny/projects/dalli/test/test_sasl.rb:46:in `block (5 levels) in <top (required)>'
---------------

[87/96] Sasl::a server requiring authentication::without authentication credentials#test_0002_gracefully handl        
  3) Failure:
Sasl::a server requiring authentication::without authentication credentials#test_0002_gracefully handle authentication failures [/home/strzibny/projects/dalli/test/test_sasl.rb:35]:
[Dalli::DalliError] exception expected, not
Class: <Dalli::RingError>
Message: <"No server available">
---Backtrace---
/home/strzibny/projects/dalli/lib/dalli/ring.rb:45:in `server_for_key'
/home/strzibny/projects/dalli/lib/dalli/client.rb:328:in `perform'
/home/strzibny/projects/dalli/lib/dalli/client.rb:103:in `set'
/home/strzibny/projects/dalli/test/test_sasl.rb:36:in `block (6 levels) in <top (required)>'
---------------

Finished tests in 15.183154s, 6.3228 tests/s, 952.3054 assertions/s.                                                  
96 tests, 14459 assertions, 2 failures, 1 errors, 0 skips
```

I would expect that the tests would be skipped if memcached is not available. Besides if I run memcached with:
```memcached -p 19124 -l localhost```

I am still getting the failures (just nothing has been raised at all):
```
$ testrb -Ilib test/test_*.rb
Testing with Rails 4.0.0
Using standard socket IO (ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux])
test/test_active_support.rb: cannot load such file -- connection_pool
Run options: -Ilib

# Running tests:

[ 6/96] Dalli::Cas::Client::using a live server#test_0001_supports get with CASFound memcached 1.4.15 in PATH
[10/96] Dalli::Cas::Client::using a live server#test_0002_supports multi-get with CAS = 0.01 s                
  1) Error:
Dalli::Cas::Client::using a live server#test_0002_supports multi-get with CAS:
NoMethodError: undefined method `second' for ["foo", 576460752303423488]:Array
    /home/strzibny/projects/dalli/test/test_cas_client.rb:44:in `block (5 levels) in <top (required)>'
    /home/strzibny/projects/dalli/test/test_cas_client.rb:43:in `each_pair'
    /home/strzibny/projects/dalli/test/test_cas_client.rb:43:in `block (4 levels) in <top (required)>'
    /home/strzibny/projects/dalli/test/memcached_mock.rb:76:in `memcached_cas'
    /home/strzibny/projects/dalli/test/test_cas_client.rb:32:in `block (3 levels) in <top (required)>'

[86/96] Sasl::a server requiring authentication#test_0001_fail SASL authentication with wrong optionsThis server is not built with SASL support.
 = 0.12 s
  2) Failure:
Sasl::a server requiring authentication#test_0001_fail SASL authentication with wrong options [/home/strzibny/projects/dalli/test/test_sasl.rb:45]:
Dalli::DalliError expected but nothing was raised.

[87/96] Sasl::a server requiring authentication::without authentication credentials#test_0002_gracefully handl        
  3) Failure:
Sasl::a server requiring authentication::without authentication credentials#test_0002_gracefully handle authentication failures [/home/strzibny/projects/dalli/test/test_sasl.rb:35]:
Dalli::DalliError expected but nothing was raised.

Finished tests in 15.957208s, 6.0161 tests/s, 906.1109 assertions/s.                                                  
96 tests, 14459 assertions, 2 failures, 1 errors, 0 skips

ruby -v: ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]
```
Am I doing something wrong or does this needs to be fixed?

**Comment by petergoldstein** [comment]
@strzibny It very much looks like you installed a version of Memcached without SASL support.  If this is still an issue, can you please confirm you install Memcached as described in the README?

Closing - please reopen if this is still a problem.
