### ISSUE TITLE
Unexpected exception in Dalli: NameError: uninitialized constant Rack::Handler::Servlet

### ISSUE THREAD

**Issue by lephyrius** [petergoldstein/dalli#450]
I use jruby-1.7.12 : 
```
 May 05 01:40:23  app/web.1: Unexpected exception in Dalli: NameError: uninitialized constant Rack::Handler::Servlet
May 05 01:40:23  app/web.1: This is a bug in Dalli, please enter an issue in Github if it does not already exist.
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/inflector/methods.rb:228:in `const_get'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/inflector/methods.rb:228:in `constantize'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/inflector/methods.rb:224:in `inject'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/inflector/methods.rb:224:in `constantize'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/core_ext/marshal.rb:10:in `load_with_autoloading'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/server.rb:424:in `deserialize'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/server.rb:488:in `generic_response'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/server.rb:257:in `get'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/server.rb:60:in `request'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/options.rb:18:in `request'
May 05 01:40:23  app/web.1: /app/vendor/ruby-1.9.3-jruby-1.7.12/lib/ruby/2.0/monitor.rb:211:in `mon_synchronize'
May 05 01:40:23  app/web.1: cache error: No server available
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/ring.rb:45:in `server_for_key'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/client.rb:328:in `perform'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/client.rb:53:in `get'
May 05 01:40:23  app/web.1: (eval):7:in `get_with_newrelic_trace'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.8.0.218/lib/new_relic/agent/method_tracer.rb:281:in `trace_execution_scoped'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.8.0.218/lib/new_relic/agent/method_tracer.rb:280:in `trace_execution_scoped'
May 05 01:40:23  app/web.1: (eval):4:in `get_with_newrelic_trace'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:324:in `read'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:30:in `lookup'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/context.rb:169:in `lookup'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/airbrake-3.1.16/lib/airbrake/user_informer.rb:16:in `_call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/airbrake-3.1.16/lib/airbrake/user_informer.rb:12:in `call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/engine.rb:511:in `call'
May 05 01:40:23  app/web.1: /app/vendor/ruby-1.9.3-jruby-1.7.12/lib/ruby/2.0/monitor.rb:210:in `mon_synchronize'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/options.rb:17:in `request'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/client.rb:329:in `perform'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/dalli-2.7.1/lib/dalli/client.rb:53:in `get'
May 05 01:40:23  app/web.1: (eval):7:in `get_with_newrelic_trace'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.8.0.218/lib/new_relic/agent/method_tracer.rb:281:in `trace_execution_scoped'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.8.0.218/lib/new_relic/agent/method_tracer.rb:280:in `trace_execution_scoped'
May 05 01:40:23  app/web.1: (eval):4:in `get_with_newrelic_trace'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:324:in `read'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:30:in `lookup'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/context.rb:169:in `lookup'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/airbrake-3.1.16/lib/airbrake/user_informer.rb:16:in `_call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/airbrake-3.1.16/lib/airbrake/user_informer.rb:12:in `call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/engine.rb:511:in `call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/application.rb:97:in `call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/railtie/configurable.rb:30:in `method_missing'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/deflater.rb:25:in `call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/puma-2.8.2-java/lib/puma/configuration.rb:71:in `call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/puma-2.8.2-java/lib/puma/server.rb:490:in `handle_request'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/puma-2.8.2-java/lib/puma/server.rb:488:in `handle_request'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/puma-2.8.2-java/lib/puma/server.rb:361:in `process_client'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/puma-2.8.2-java/lib/puma/server.rb:357:in `process_client'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/puma-2.8.2-java/lib/puma/server.rb:254:in `run'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/puma-2.8.2-java/lib/puma/thread_pool.rb:92:in `call'
May 05 01:40:23  app/web.1: /app/vendor/bundle/jruby/1.9/gems/puma-2.8.2-java/lib/puma/thread_pool.rb:92:in `spawn_thread' 
```

**Comment by petergoldstein** [comment]
Closing.
