### ISSUE TITLE
Single server socket retry behavior

### ISSUE THREAD

**Issue by brettbuddin** [petergoldstein/dalli#507]
It appears that Dalli isn't performing any socket retry behavior when a single server is provided to the client. Is this expected behavior, or should the `socket_max_failures` option still be honored in this situation?

I'd expect it to attempt to connect at most 10 times in the example below, but it is only trying once:

```
irb(main):001:0> Dalli::Client.new('narnia.io:1234', {socket_max_failures: 10, socket_failure_delay: 1}).get('test-key')
D, [2014-12-15T18:18:45.099946 #8494] DEBUG -- : Dalli::Server#connect narnia.io:1234
I, [2014-12-15T18:18:45.211772 #8494]  INFO -- : narnia.io:1234 failed (count: 0) Timeout::Error: execution expired
Dalli::RingError: No server available
        from /home/vagrant/.bundle/gems/dalli-2.7.2/lib/dalli/ring.rb:45:in `server_for_key'
        from /home/vagrant/.bundle/gems/dalli-2.7.2/lib/dalli/client.rb:328:in `perform'
        from /home/vagrant/.bundle/gems/dalli-2.7.2/lib/dalli/client.rb:53:in `get'
        from (irb):1
        from /home/vagrant/.rbenv/versions/2.1.4/bin/irb:11:in `<main>'
irb(main):002:0>
```

**Comment by eivindm** [comment]
This is an issue for us, and the documentation still refers to the behavior that do not work. What is the future for this feature? Thanks in advance!
