### ISSUE TITLE
Unexpected exception in Dalli: ArgumentError: string contains null byte

### ISSUE THREAD

**Issue by ErGisler** [petergoldstein/dalli#529]
Hello,

I got a problem with Dalli 2.7.2, memcached 1.4.4

```
This is a bug in Dalli, please enter an issue in Github if it does not already exist.
/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/core_ext/marshal.rb:6:in `_load'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/core_ext/marshal.rb:6:in `load'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/dalli/server.rb:424:in `deserialize'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/dalli/server.rb:488:in `generic_response'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/dalli/server.rb:257:in `get'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/dalli/server.rb:60:in `request'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/dalli/options.rb:18:in `block in request'
	/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/dalli/options.rb:17:in `request'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/dalli/client.rb:329:in `perform'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/dalli/client.rb:53:in `get'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/rack/session/dalli.rb:31:in `block in get_session'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/rack/session/dalli.rb:61:in `with_lock'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/dalli-2.7.2/lib/rack/session/dalli.rb:30:in `get_session'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:266:in `load_session'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/session/abstract_store.rb:43:in `block in load_session'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/session/abstract_store.rb:43:in `load_session'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/request/session.rb:168:in `load!'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/request/session.rb:164:in `load_for_write!'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/request/session.rb:106:in `[]='
	/home/m2/app/controllers/application_controller.rb:141:in `set_charset'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:387:in `_run__2665950635715412744__process_action__callbacks'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:17:in `process_action'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:136:in `process'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:44:in `process'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/session_off-0.5.0/lib/session_off.rb:176:in `process_with_session_off'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_controller/metal.rb:195:in `dispatch'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_controller/metal.rb:231:in `block in action'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:48:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:71:in `block in call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `each'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:655:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb:241:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb:486:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activerecord-4.0.0/lib/active_record/query_cache.rb:36:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:373:in `_run__1029456427082247305__call__callbacks'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/railties-4.0.0/lib/rails/rack/logger.rb:38:in `call_app'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `block in call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `block in tagged'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:25:in `tagged'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `tagged'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/actionpack-4.0.0/lib/action_dispatch/middleware/static.rb:64:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/railties-4.0.0/lib/rails/engine.rb:511:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/railties-4.0.0/lib/rails/application.rb:97:in `call'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/passenger-4.0.14/lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/passenger-4.0.14/lib/phusion_passenger/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/passenger-4.0.14/lib/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'
	/usr/local/rvm/gems/ruby-2.0.0-p247@x5/gems/passenger-4.0.14/lib/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'
localhost:11211 is down
#<Dalli::NetworkError: localhost:11211 is down: ArgumentError string contains null byte>
retrying request with new server
down_retry_delay not reached for localhost:11211 (1.000 seconds left)
```

This happened only when one particular page was being loaded.
It was trying to access **session[:some_value] = 0 if session**

But after using
```
$ memcached restart
```
Fixed the issue. But I believe that this is just a matter of time, when it will reproduce.

**Comment by petergoldstein** [comment]
They key part of the trace is this - "string contains null byte".  This indicates a string value with a NUL byte was being returned by the fetch.  Were you using any non-Ruby code to insert into Memcached?  This very much looks like a data error.

**Comment by ErGisler** [comment]
Well memchaced is only used by Ruby on Rails application (Apache, Mysql, JavaScript, Ruby-2.0.0 as for that specific page). I have tried manually insert null byte value into session (***session[:value] = "ab\0ba"***), but Rails 4 handled it ok. Also tried creating a DB record using same value with success.

There is no non-Ruby code which could have somehow interact with memcached. Unless OS/memcached itself somehow corrupted it.

**Comment by petergoldstein** [comment]
@ErGisler Did you ever see this error recur?

**Comment by ErGisler** [comment]
I haven't encountered this issue anymore, or at least no one reported it to me so far. 
We are no longer using ruby-2.0.0, but rather 2.1.2, so it may have had an effect, but its just a guess.

**Comment by petergoldstein** [comment]
Given this issue isn't recurring, and hasn't been reported by anyone else, I'm going to close the issue.
