### ISSUE TITLE
Issue with dalli connection throwing unknown error

### ISSUE THREAD

**Issue by ashish-sjc** [petergoldstein/dalli#564]
http://stackoverflow.com/questions/33400094/issue-with-dalli-not-working-as-expectd

I have a simple rails app and I am trying to save and retrieve keys from a memcache box, which was working for a long time unless we started encountering the error below, I have tried debugging this but will need someone to help now

```ruby
[2015-10-28 12:25:46.649][ERROR] Unexpected exception during Dalli request: NoMethodError: undefined method `<<' for nil:NilClass (pid:58452)
[2015-10-28 12:25:46.649][ERROR] /Users/aupadhyay/.rvm/gems/ruby-2.2.2/gems/celluloid-0.17.2/lib/celluloid/proxy/async.rb:28:in `method_missing'
/Users/aupadhyay/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/core_ext/marshal.rb:6:in `load'
```

I am using `Rails.cache.fetch` & `Rails.cache.write` as usual, request some help on this.

**Comment by petergoldstein** [comment]
I'm not sure how we could help you without seeing the underlying code.  Closing.
