### ISSUE TITLE
Infine loop with Errno::ECONNRESET

### ISSUE THREAD

**Issue by dadah89** [petergoldstein/dalli#657]
Had an issue with Dalli::Client#perform getting into an infinite loop, this is what the logs looked like:
```
0.0.0.1:11211 failed (count: 0) Errno::ECONNRESET: Connection reset by peer - send
#<Dalli::NetworkError: Socket operation failed, retrying...>
retrying request with new server
Dalli::Server#connect 0.0.0.1:11211
0.0.0.1:11211 failed (count: 0) Errno::ECONNRESET: Connection reset by peer - send
#<Dalli::NetworkError: Socket operation failed, retrying...>
retrying request with new server
Dalli::Server#connect 0.0.0.1:11211
0.0.0.1:11211 failed (count: 0) Errno::ECONNRESET: Connection reset by peer - send
#<Dalli::NetworkError: Socket operation failed, retrying...>
```
Even though it was configured dozens of servers, it would always try the same one (I modified the ip above, but it was always the same server).

It happened with version 2.7.4

Reading the code and testing locally, I'm not sure how it might've happened. Because failed count was always 0 (and the `Dalli::Server#connect` line above), looks like it would need `server.active?` (probably within `ring.server_for_key` ?) to succeed (so `up!` gets called, resetting `@failed_count`) , and then `server.request` raise `Errno::ECONNRESET`. Any ideas about how it got in that state?

I checked the repo and did many tests with 2.7.4 and 2.7.6, couldn't reproduce locally (besides manually raising exceptions), but looks like 2.7.6 changes wouldn't prevent the infinite loop, from what I can tell.

Thanks!

**Comment by dadah89** [comment]
Monkey patched `perform` to add some logging, got a stack trace:

```
dalli-2.7.6/lib/dalli/server.rb:220:in `reconnect!'
dalli-2.7.6/lib/dalli/server.rb:231:in `failure!'
dalli-2.7.6/lib/dalli/server.rb:559:in `rescue in write'
dalli-2.7.6/lib/dalli/server.rb:553:in `write'
dalli-2.7.6/lib/dalli/server.rb:291:in `block in set'
dalli-2.7.6/lib/dalli/server.rb:476:in `guard_max_value'
dalli-2.7.6/lib/dalli/server.rb:289:in `set'
dalli-2.7.6/lib/dalli/server.rb:67:in `request'
dalli-2.7.6/lib/dalli/options.rb:18:in `block in request'
  opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
dalli-2.7.6/lib/dalli/options.rb:17:in `request'
  config/initializers/dalli.rb:28:in `perform'
dalli-2.7.6/lib/dalli/client.rb:126:in `set'
newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/memcache.rb:48:in `block (levels) in instrument_methods'",
newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:73:in `block itrace_execution_scoped'",
newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer_helpers.rb:82:i`trace_execution_scoped'",
newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:71:intrace_execution_scoped'",
newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/memcache.rb:45:in `block (levels) in instrument_methods'",
dalli-2.7.6/lib/active_support/cache/dalli_store.rb:314:in `write_entry'
activesupport-4.2.8/lib/active_support/cache/strategy/local_cache.rb:115:in `write_entry'
dalli-2.7.6/lib/active_support/cache/dalli_store.rb:144:in `block (2 levels) in write'
dalli-2.7.6/lib/dalli/client.rb:262:in `with'
dalli-2.7.6/lib/active_support/cache/dalli_store.rb:82:in `with'
dalli-2.7.6/lib/active_support/cache/dalli_store.rb:142:in `block in write'
dalli-2.7.6/lib/active_support/cache/dalli_store.rb:371:in `block in instrument'
activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
dalli-2.7.6/lib/active_support/cache/dalli_store.rb:371:in `instrument'
dalli-2.7.6/lib/active_support/cache/dalli_store.rb:141:in `write'
```

**Comment by sobrinho** [comment]
@dadah89 can you make a PR?

**Comment by dadah89** [comment]
@sobrinho sorry it took me so long to answer =\ I'm still not sure how it gets to that state, so I'd need some help understanding what's wrong... I've patched `perform` to raise `Dalli::RingError` after a some tries, but feels more like a hack than a proper solution, something along the lines:

```rb
def perform(*all_args)
  return yield if block_given?
  op, key, *args = *all_args

  key = key.to_s
  key = validate_key(key)

  begin
    server = ring.server_for_key(key)
    ret = server.request(op, key, *args)
    ret
  rescue NetworkError => e
    Dalli.logger.debug { e.inspect }
    Dalli.logger.debug { 'retrying request with new server' }

    @perform_retry_fail ||= 0

    Dalli.logger.debug "Dalli::Client#perform error - failed count: #{@perform_retry_fail} op: #{op} key: #{key} server: #{server.try(:name)}"

    @perform_retry_fail += 1

    if @perform_retry_fail >= 5
      @perform_retry_fail = 0
      Dalli.logger.error 'Too many retry failures, marking all servers dead'
      Dalli.logger.error e.backtrace
      raise Dalli::RingError, 'No server available'
    end

    retry
  end
end
```
