### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by dadah89** [petergoldstein/dalli#658]
Last one is from Feb 2016, so whenever someone has some time it'd be nice to release a new one =)

**Comment by kyanagi** [comment]
With Ruby 2.5.0-preview1, Dalli 2.7.6 raises an error.

```
% ruby -v -rdalli -e 'p Dalli::VERSION; p Dalli::Client.new("localhost:11211").get("foo")'
ruby 2.5.0preview1 (2017-10-10 trunk 60153) [x86_64-darwin16]
/Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/server.rb:701: warning: assigned but unused variable - type
"2.7.6"
Traceback (most recent call last):
	16: from -e:1:in `<main>'
	15: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/client.rb:58:in `get'
	14: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/client.rb:361:in `perform'
	13: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/ring.rb:42:in `server_for_key'
	12: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/options.rb:23:in `alive?'
	11: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	10: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/options.rb:24:in `block in alive?'
	 9: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/server.rb:95:in `alive?'
	 8: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/server.rb:589:in `connect'
	 7: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/server.rb:395:in `version'
	 6: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/server.rb:355:in `write_generic'
	 5: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/server.rb:498:in `generic_response'
	 4: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/server.rb:575:in `read_header'
	 3: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/server.rb:566:in `read'
	 2: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/socket.rb:32:in `readfull'
	 1: from /Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/socket.rb:32:in `kgio_read!'
/Users/ani/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/dalli-2.7.6/lib/dalli/socket.rb:19:in `kgio_wait_readable': wrong number of arguments (given 24, expected 0) (ArgumentError)
```

Dalli HEAD seems to be OK.

**Comment by andrewjaanuu** [comment]
+1

**Comment by magnusvk** [comment]
+1 anything on this?

**Comment by englertjoseph** [comment]
@kyanagi I also ran into this problem when using ruby 2.5.0, updating the kgio gem seems to have fixed it for me.

**Comment by exosty** [comment]
+1. Any news?

**Comment by petergoldstein** [comment]
2.7.7 has been released.

**Comment by axelson** [comment]
What are the highlights in 2.7.7?
