### ISSUE TITLE
`deadlock; recursive locking` under heavy load with slow `Rails.cache.fetch`

### ISSUE THREAD

**Issue by cesarizu** [petergoldstein/dalli#731]
Hi,

I'm running a rails app on Heroku. Under heavy load, I've seen this error a few times. The ruby vm is locked and the only thing that works is restarting the server. The code that triggers the error is similar to:

```ruby
Rails.cache.fetch("some_cache_#{key}", expires_in: 0) { get_cache_value(key) }
```

The full error is the following:

```
deadlock; recursive locking
/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:189:in `lock'
/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:189:in `mon_enter'
/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:228:in `mon_synchronize'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/dalli/options.rb:24:in `alive?'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/dalli/ring.rb:43:in `server_for_key'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/memcache/dalli.rb:41:in `server_for_key'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/dalli/client.rb:367:in `perform'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/dalli/client.rb:59:in `get'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/memcache.rb:49:in `block (3 levels) in instrument_methods'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:306:in `block in read_entry'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/dalli/client.rb:266:in `with'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:87:in `with'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:306:in `read_entry'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache.rb:124:in `block in read_entry'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache.rb:78:in `block in fetch_entry'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache.rb:78:in `fetch'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache.rb:78:in `fetch_entry'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache.rb:124:in `read_entry'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:420:in `read_entry'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:107:in `block in fetch'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:389:in `block in instrument_with_log'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:398:in `block in instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:397:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:389:in `instrument_with_log'
/app/vendor/bundle/ruby/2.6.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:106:in `fetch'
```

Seems related to petergoldstein/dalli#193 but in that case there seems to be no exception like this one.

Is this a Dalli bug?

**Comment by aliou** [comment]
Having a similar issue. @cesarizu Have you found a solution ?

**Comment by drdrsh** [comment]
@aliou I think this is likely due to a bug in Ruby that was [fixed in version 2.6.5](https://github.com/ruby/ruby/commit/9ab43c7a6c0dc3c661ffb621714ee0c62bdd4566#diff-abcaf64fd274b3e9f1a2ff6ba8f73820).

**Comment by cesarizu** [comment]
I haven't seen this error in some time. We did update Ruby and it seems to be gone.

**Comment by knightq** [comment]
No, it's not: we still have it on ruby 2.6.6
