### ISSUE TITLE
Dalli::MarshalError is not instrumented like other errors

### ISSUE THREAD

**Issue by bak1an** [petergoldstein/dalli#744]
With dalli 2.7.10 `Dalli::MarshalError` is logged but is not sent to instrumentation.

Example snippet that correctly receives error notification when memcached is stopped:

```
> ActiveSupport::Notifications.subscribe(/cache_.+\.active_support/) { |*args| puts "cache event: #{args}" }
...

> Rails.cache.write 'something', 'value'
cache event: ["cache_error.active_support", 2020-04-08 16:02:55 -0300, 2020-04-08 16:02:55 -0300, "702c310eae852f81a822", {:key=>"DalliError", :message=>"No server available"}]
cache event: ["cache_write.active_support", 2020-04-08 16:02:55 -0300, 2020-04-08 16:02:55 -0300, "702c310eae852f81a822", {:key=>"something"}]
=> false
```

But when the memcached is running and I am trying to cache something non marshallable the error is not instrumented:
```
> ActiveSupport::Notifications.subscribe(/cache_.+\.active_support/) { |*args| puts "cache event: #{args}" }
...

> Rails.cache.write 'something', -> { 'no marshalling for this one' }
cache event: ["cache_write.active_support", 2020-04-08 16:05:15 -0300, 2020-04-08 16:05:15 -0300, "702c310eae852f81a822", {:key=>"something"}]
=> false
```

But I can see it in logs:
``` 
Marshalling error for key 'dev:something': no _dump_data is defined for class Proc
You are trying to cache a Ruby object which cannot be serialized to memcached.
/Users/bak1an/.rvm/gems/ruby-2.3.6@di/gems/dalli-2.7.10/lib/dalli/server.rb:413:in `dump'
	/Users/bak1an/.rvm/gems/ruby-2.3.6@di/gems/dalli-2.7.10/lib/dalli/server.rb:413:in `serialize'
	/Users/bak1an/.rvm/gems/ruby-2.3.6@di/gems/dalli-2.7.10/lib/dalli/server.rb:285:in `set'
	/Users/bak1an/.rvm/gems/ruby-2.3.6@di/gems/dalli-2.7.10/lib/dalli/server.rb:70:in `request'
	/Users/bak1an/.rvm/gems/ruby-2.3.6@di/gems/dalli-2.7.10/lib/dalli/options.rb:19:in `block in request'
...
```

Looking at the code I would expect MarshalError to be instrumented just as the other errors, not sure why it is not happening now.

**Comment by bak1an** [comment]
Found the place where MarshalError is consumed - https://github.com/petergoldstein/dalli/blob/master/lib/dalli/server.rb#L71
